apiVersion: v2
name: streamflow
description: A Helm chart for StreamFlow real-time analytics platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - analytics
  - streaming
  - real-time
  - data-pipeline
  - monitoring
home: https://github.com/streamflow/streamflow
sources:
  - https://github.com/streamflow/streamflow
maintainers:
  - name: StreamFlow Team
    email: team@streamflow.io
dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: rabbitmq
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
annotations:
  category: Analytics
  licenses: MIT 