groups:
  - name: streamflow_alerts
    rules:
      - alert: HighLatency
        expr: avg_response_time > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "Average response time is above 1000ms for 5 minutes"

      - alert: HighErrorRate
        expr: error_rate > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 2 minutes"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "Service has been down for more than 1 minute"
