apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: streamflow-webhook
webhooks:
- name: streamflow.webhook.io
  clientConfig:
    service:
      name: streamflow-webhook
      namespace: streamflow-webhook
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuRENDQTRTZ0F3SUJBZ0lVWndEeFNhS0FTN2t5UEhCMS9rYnBtYklyTGdVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZMHhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeQpZVzVqYVhOamJ6RVRNQkVHQTFVRUNnd0tVM1J5WldGdFJteHZkekVRTUE0R0ExVUVDd3dIVjJWaWFHOXZhekV5Ck1EQUdBMVVFQXd3cGMzUnlaV0Z0Wm14dmR5MTNaV0pvYjI5ckxuTjBjbVZoYldac2IzY3RkMlZpYUc5dmF5NXoKZG1Nd0hoY05NalV3TnpJek1Ua3lNakV4V2hjTk1qWXdOekl6TVRreU1qRXhXakNCalRFTE1Ba0dBMVVFQmhNQwpWVk14Q3pBSkJnTlZCQWdNQWtOQk1SWXdGQVlEVlFRSERBMVRZVzRnUm5KaGJtTnBjMk52TVJNd0VRWURWUVFLCkRBcFRkSEpsWVcxR2JHOTNNUkF3RGdZRFZRUUxEQWRYWldKb2IyOXJNVEl3TUFZRFZRUUREQ2x6ZEhKbFlXMW0KYkc5M0xYZGxZbWh2YjJzdWMzUnlaV0Z0Wm14dmR5MTNaV0pvYjI5ckxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWVJWDFvN3FlTmVKMlhvMG15YVhiNU1uZ1hwTmtZRFhtUmFSTW9SCkRVdTNQeU1jaVhNNW1QN2Q1YzQxL2pOMnZZMlpZRjlIRExXMmV1VEJpenFaQytoYnVGZ3dJOE9VcUVDc3AxbGUKOVlldWhzQmk0ZTFQT09BamxtbVF1MWVBOHJoUGM1QjRyVjJLN01YY0FTOXUzcG1CMWRSdnZtNnNHanV5UlBCeAptY3JMQmNoZDVSVWowVVFxaGY1RFdjZGN5aUtIeTJRN3UyWWg2QUc0VksyU3lkbm1pNzRLdC93cGlibDIwZXVFCnJDR3ljdXhHVzMxUE1sbEp2eFEzaC9uMHRDajFqWm4yS2NQNnRaQVo0MWFXbUJBak5VbmZsSmR2ckRJbHROeU8KOGJEc2R5UWhyekxBVlgwektVRUNkQ0k0UmJJVVdyUXMwWjhXVlV3bjYyOFdKYk1DQXdFQUFhT0I4VENCN2pBTApCZ05WSFE4RUJBTUNCREF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd2dhb0dBMVVkRVFTQm9qQ0JuNElTCmMzUnlaV0Z0Wm14dmR5MTNaV0pvYjI5cmdpVnpkSEpsWVcxbWJHOTNMWGRsWW1odmIyc3VjM1J5WldGdFpteHYKZHkxM1pXSm9iMjlyZ2lsemRISmxZVzFtYkc5M0xYZGxZbWh2YjJzdWMzUnlaV0Z0Wm14dmR5MTNaV0pvYjI5cgpMbk4yWTRJM2MzUnlaV0Z0Wm14dmR5MTNaV0pvYjI5ckxuTjBjbVZoYldac2IzY3RkMlZpYUc5dmF5NXpkbU11ClkyeDFjM1JsY2k1c2IyTmhiREFkQmdOVkhRNEVGZ1FVdjlZbC9oMGZXWk9SS2VEMWZRdGQxbzJ6Y0hnd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBR2NIUXpqTzR1SUZ6WG5FaXdlSE9nQmFkeko4VU1mR1VnelUrSjdyKzdGbQpmVUZDTkMrcVVNbXZXUnorNklNOXpWQk9GOG02SHB0OGZ3N2JNc1BjM2dVam00RytjVnlCc2M3TGduQmIzanVUCk9RbXlVa29WYzJISVRiaW5GczNEazMySTdiRHpLYzlvNUtGYzJCZHhEYkNJMWpicnV3alU5ellZVXF2RmVqaGoKTXg0aExuVjhSYStraEhmOW1vZEhKUkJrQTR2Nml2VlpZTHdqVXd2MzZyczdGQWpodUV0RkNtSnlHK0VmaEZKQQovdVltb2JvU2ZEQjJhZW1ya3FQNFd0ZjdHZkwwY2kxakU0ZTdxSm1MczVUUDV0VG01QTFLOVBVRzRmT2lmdHFYCkd2U1psWktwUFIwemVhV0JacmExSSs0TE1sanhYRHJJbldEdzlzVldKUmM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps", ""]
    apiVersions: ["v1"]
    resources: ["deployments", "services"]
  namespaceSelector:
    matchExpressions:
    - key: streamflow.io/webhook
      operator: NotIn
      values: ["disabled"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
